-- Football data schema (Phase 1)

CREATE TABLE IF NOT EXISTS competitions (
    id               SERIAL PRIMARY KEY,
    api_football_id  INTEGER UNIQUE NOT NULL,
    name             VARCHAR(100) NOT NULL,
    country          VARCHAR(100),
    logo_url         TEXT,
    season           INTEGER NOT NULL,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS teams (
    id               SERIAL PRIMARY KEY,
    api_football_id  INTEGER UNIQUE NOT NULL,
    name             VARCHAR(100) NOT NULL,
    short_name       VARCHAR(20),
    logo_url         TEXT,
    country          VARCHAR(100),
    founded          INTEGER,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS players (
    id               SERIAL PRIMARY KEY,
    api_football_id  INTEGER UNIQUE NOT NULL,
    name             VARCHAR(100) NOT NULL,
    firstname        VARCHAR(100),
    lastname         VARCHAR(100),
    nationality      VARCHAR(100),
    position         VARCHAR(50),
    date_of_birth    DATE,
    height           VARCHAR(10),
    weight           VARCHAR(10),
    photo_url        TEXT,
    team_id          INTEGER REFERENCES teams(id),
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS standings (
    id               SERIAL PRIMARY KEY,
    competition_id   INTEGER REFERENCES competitions(id),
    team_id          INTEGER REFERENCES teams(id),
    season           INTEGER NOT NULL,
    rank             INTEGER,
    played           INTEGER DEFAULT 0,
    wins             INTEGER DEFAULT 0,
    draws            INTEGER DEFAULT 0,
    losses           INTEGER DEFAULT 0,
    goals_for        INTEGER DEFAULT 0,
    goals_against    INTEGER DEFAULT 0,
    goal_difference  INTEGER DEFAULT 0,
    points           INTEGER DEFAULT 0,
    form             VARCHAR(20),
    last_synced_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (competition_id, team_id, season)
);

CREATE TABLE IF NOT EXISTS fixtures (
    id               SERIAL PRIMARY KEY,
    api_football_id  INTEGER UNIQUE NOT NULL,
    competition_id   INTEGER REFERENCES competitions(id),
    home_team_id     INTEGER REFERENCES teams(id),
    away_team_id     INTEGER REFERENCES teams(id),
    kickoff_time     TIMESTAMPTZ,
    matchday         INTEGER,
    status           VARCHAR(20),
    home_score       INTEGER,
    away_score       INTEGER,
    venue_name       VARCHAR(100),
    referee          VARCHAR(100),
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS player_season_stats (
    id                  SERIAL PRIMARY KEY,
    player_id           INTEGER REFERENCES players(id),
    competition_id      INTEGER REFERENCES competitions(id),
    team_id             INTEGER REFERENCES teams(id),
    season              INTEGER NOT NULL,
    appearances         INTEGER DEFAULT 0,
    lineups             INTEGER DEFAULT 0,
    minutes_played      INTEGER DEFAULT 0,
    position            VARCHAR(50),
    rating              NUMERIC(4,2),
    captain             BOOLEAN DEFAULT FALSE,
    subs_in             INTEGER DEFAULT 0,
    subs_out            INTEGER DEFAULT 0,
    bench               INTEGER DEFAULT 0,
    shots_total         INTEGER DEFAULT 0,
    shots_on_target     INTEGER DEFAULT 0,
    goals_total         INTEGER DEFAULT 0,
    goals_conceded      INTEGER DEFAULT 0,
    goal_assists        INTEGER DEFAULT 0,
    goal_saves          INTEGER,
    passes_total        INTEGER DEFAULT 0,
    passes_key          INTEGER DEFAULT 0,
    passes_accuracy     INTEGER,
    tackles_total       INTEGER DEFAULT 0,
    tackles_blocks      INTEGER DEFAULT 0,
    interceptions       INTEGER DEFAULT 0,
    duels_total         INTEGER DEFAULT 0,
    duels_won           INTEGER DEFAULT 0,
    dribbles_attempts   INTEGER DEFAULT 0,
    dribbles_success    INTEGER DEFAULT 0,
    fouls_drawn         INTEGER DEFAULT 0,
    fouls_committed     INTEGER DEFAULT 0,
    yellow_cards        INTEGER DEFAULT 0,
    yellow_red_cards    INTEGER DEFAULT 0,
    red_cards           INTEGER DEFAULT 0,
    penalty_won         INTEGER DEFAULT 0,
    penalty_committed   INTEGER DEFAULT 0,
    penalty_scored      INTEGER DEFAULT 0,
    penalty_missed      INTEGER DEFAULT 0,
    penalty_saved       INTEGER DEFAULT 0,
    last_synced_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (player_id, competition_id, team_id, season)
);

CREATE TABLE IF NOT EXISTS player_match_stats (
    id                  SERIAL PRIMARY KEY,
    player_id           INTEGER REFERENCES players(id),
    fixture_id          INTEGER REFERENCES fixtures(id),
    team_id             INTEGER REFERENCES teams(id),
    minutes_played      INTEGER,
    position            VARCHAR(50),
    rating              NUMERIC(4,2),
    offsides            INTEGER DEFAULT 0,
    shots_total         INTEGER DEFAULT 0,
    shots_on_target     INTEGER DEFAULT 0,
    goals               INTEGER DEFAULT 0,
    goal_assists        INTEGER DEFAULT 0,
    goals_conceded      INTEGER DEFAULT 0,
    goal_saves          INTEGER,
    passes_total        INTEGER DEFAULT 0,
    passes_accuracy     INTEGER,
    key_passes          INTEGER DEFAULT 0,
    tackles             INTEGER DEFAULT 0,
    tackles_blocks      INTEGER DEFAULT 0,
    interceptions       INTEGER DEFAULT 0,
    duels_total         INTEGER DEFAULT 0,
    duels_won           INTEGER DEFAULT 0,
    dribbles_attempts   INTEGER DEFAULT 0,
    dribbles_success    INTEGER DEFAULT 0,
    dribbles_past       INTEGER DEFAULT 0,
    fouls_drawn         INTEGER DEFAULT 0,
    fouls_committed     INTEGER DEFAULT 0,
    yellow_cards        INTEGER DEFAULT 0,
    red_cards           INTEGER DEFAULT 0,
    penalty_won         INTEGER DEFAULT 0,
    penalty_committed   INTEGER DEFAULT 0,
    penalty_scored      INTEGER DEFAULT 0,
    penalty_missed      INTEGER DEFAULT 0,
    penalty_saved       INTEGER DEFAULT 0,
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (player_id, fixture_id)
);

CREATE TABLE IF NOT EXISTS fixture_team_stats (
    id                  SERIAL PRIMARY KEY,
    fixture_id          INTEGER REFERENCES fixtures(id),
    team_id             INTEGER REFERENCES teams(id),
    shots_on_goal       INTEGER,
    shots_off_goal      INTEGER,
    total_shots         INTEGER,
    blocked_shots       INTEGER,
    shots_inside_box    INTEGER,
    shots_outside_box   INTEGER,
    fouls               INTEGER,
    corner_kicks        INTEGER,
    offsides            INTEGER,
    ball_possession     INTEGER,
    yellow_cards        INTEGER,
    red_cards           INTEGER,
    goalkeeper_saves    INTEGER,
    total_passes        INTEGER,
    passes_accurate     INTEGER,
    passes_pct          INTEGER,
    expected_goals      NUMERIC(4,2),
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (fixture_id, team_id)
);
